### ISSUE TITLE
Glitch with the Asteroid Mining

### ISSUE THREAD

**Issue by DrNathan100** [7yl4r/the-oregon-trajectory#103]
Hi there, play tester from Ludust here. I played the game for the first time yesterday and I really enjoyed it! Hopefully I'm posting this to the right place, but I did have one glitch come up.

When the asteroid mini game would come up, it would be the same asteroid as the last time I played it, even after I mined out the asteroid to literally nothing, a new one would not spawn the next game, and the game would not end on it's own without me going out of bounds.

**Comment by 7yl4r** [comment]
ooooh! good catch! This one's my fault, I think I know just what to do.
