### ISSUE TITLE
End Screen Glitch.

### ISSUE THREAD

**Issue by DrNathan100** [7yl4r/the-oregon-trajectory#104]
Hi there! Playtester from Ludust here. Hoping this is the write place to post this, I came across a very interesting end game screen. obviously it isn't supposed to look like this so, here I am reporting the issue.
![endscreen](https://cloud.githubusercontent.com/assets/5965786/7672691/ed55a34e-fcb0-11e4-8f28-020b351cb450.png)

**Comment by 7yl4r** [comment]
Yeah, those end-game screens have some layout issues. This looks like the winning screen... I think? When did it pop up?

**Comment by DrNathan100** [comment]
I think it was the winning screen that ends at Europa

**Comment by 7yl4r** [comment]
Ok. We'll have to re-work that. If you have any less concrete feedback about the game I'm on the [gitter chat](https://gitter.im/7yl4r/the-oregon-trajectoryl) now to discuss as well.
