### ISSUE TITLE
SFX of rockets continue when failing Asteroid Mini game

### ISSUE THREAD

**Issue by Shubeans** [7yl4r/the-oregon-trajectory#118]
After failing a asteroid mini game by flying too far off screen, the SFX contiues to play for a few seconds once the user is back on the main trajectory mission.

Severity:
Minor issue.

Reproduction rate:
5/5

Tested on:
Chrome: version 43.0

**Comment by 7yl4r** [comment]
Confirmed. I've seen this too. Should be fixed along with the phaser-muting.

**Comment by JrodManU** [comment]
I was checking out the project and saw that I had a ship named after me. I felt it mandatory to find something to fix :)
