### ISSUE TITLE
Floating crew member obscures text on End Screen

### ISSUE THREAD

**Issue by Shubeans** [7yl4r/the-oregon-trajectory#120]
When dying of low food rations (untested on fuel), there is a splash screen in which 3 crew members a floating in space, and text explaining the the user that they are have just died.
Currently one crew image is floating infront of the text, obscuring it from view.
Either this image should be behind the text, or in a different location.

Severity:
Minor issue

Reproduction Rate:
5/5

Tested on:
Chrome version 43.0
Screen Resolution:
1366 x 768
![icon_clipping](https://cloud.githubusercontent.com/assets/3648210/8019980/e6c3e0f4-0c5f-11e5-8460-c2d2d85b9bf9.jpg)
##

**Comment by 7yl4r** [comment]
closing this legacy issue to clear the issue tracker, but it remains open and tracked on the [legacy project board](https://github.com/7yl4r/the-oregon-trajectory/projects/3)
