### ISSUE TITLE
game design document

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#14]
Need to document:

* the game story
* characters
* ~~game modules~~
*  ~~the planned trajectory~~
* ~~art style~~
* ~~sound/music~~
* ~~UI~~

**Comment by MrNubbin** [comment]
Planned trajectory has been documented. Working on the game story next. I don't want to steal your thunder with the story writing, I'm just hitting the points that were discussed in other threads.

**Comment by 7yl4r** [comment]
No thunder stealing at all! I've actually been a bit worried that we don't have any dedicated writers so I'm a bit relieved. Go for it! Also feel free to close off the issue if you feel you've resolved it.

**Comment by 7yl4r** [comment]
doh. closed the wrong issue. this one only partially resolved.

**Comment by MrNubbin** [comment]
I was about to say! haha I'm not crazy about writing but once I knock out the trajectory I'm not good for much else. I'm gonna work on this first so that everyone has a baseline. Essentially all my trajectory gives us at this point is a map screen, so it can wait.

**Comment by 7yl4r** [comment]
The trajectory is very important so the artists know what to work on though. I think I've managed to confuse myself here; do you want to draft the story or should I reassign that one?

**Comment by MrNubbin** [comment]
I'll work on the story, and I'm gonna get it mostly squared away except for the finer details before I knock out the trajectory.
