### ISSUE TITLE
find a fit for a cosmosium scene

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#16]
I'd really like to find a way to pull in a scene or two from cosmosium, but I don't want it to seem forced. Is there a place for a webGl scene in here somewhere? Maybe even not along the core gameplay, but as a "learn more" section as we pass through the asteroid belt?

Or maybe the asteroid belt "location art" can be a webGl scene? 

What do you think @BrianErikson?
##

**Comment by BrianErikson** [comment]
The texel art is going to make this one a tough sell. We might be able to incorporate the scene as an easter egg somewhere, but it definitely doesn't with the main scheme of things. I would've said a mission planner, but we both now how insanely hard that is to actually do.

I think it would look great as a main-menu background however. Run a blur shader pass over it, and it would look amazing.

**Comment by 7yl4r** [comment]
I guess the game I'm envisioning isn't nearly as tied to this texel style. What if we find a more abstract use for it? For instance... as a scoreboard; bigger asteroids are "claimed" by the top scorers.

**Comment by 7yl4r** [comment]
closing this legacy issue to clear the issue tracker, but it remains open and tracked on the [legacy project board](https://github.com/7yl4r/the-oregon-trajectory/projects/3)
