### ISSUE TITLE
background art

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#20]
art for the background of the traveling screen. These need to keep a relatively consistent art style, since this art scrolls by behind @JrodManU's sprites as the player moves between locations. Don't forget to ask: Does it blend? =P

I think we want a set height of either 400 or 600px, and we'll make them VERY wide... Ideally scaled to distance between locations... although, this is very hard to figure out until we have locations set. Perhaps it is better to do this as a set of interlocking tiles which we can stack. Like so:

    [earth->space tile] + [space tile]x3 + [space->moon tile] + [inverted space->moon tile] + [space tile]x10

We might want to include multiple layers traveling and different speeds for a parallax effect. For multiple layers traversing at different speeds, the setup is the same, but layers which move faster must have bigger tiles.

    [slow earth tile w=10] + [slow tile space w=10]
    [fast earth tile w=20] + [fast tile space w=20]

Does that make sense?

**Comment by terpin** [comment]
This makes sense. Do you know how wide they would be, though?

**Comment by 7yl4r** [comment]
I think the width just depends on how fast we want to move them across the screen. I'm not sure what a good metric of this is, but my random guess in pixels/sec maybe on the order of magnitude of 10 for the slowest layer? (I think it makes sense to start with the slower layers and add faster later, right?)

I think these tiles can be varied lengths too, I don't think we need to pick a set size do we?

**Comment by terpin** [comment]
Well it wouldn't be tiled (it could be, but looking at the same thing for
the whole game might get a little boring), it'd be a big wide parallax file
that it would slowly/quickly roll across. So if the image was say, 2200
pixels wide, that would take about 4 minutes to cross at 10px/second. We
need a standardized size or to know how long the trip between destinations
will be to keep it all in sync

**Comment by MrNubbin** [comment]
Crazy idea, do we want to throw in cryogenics? If we put them into cryosleep then we can create standard distances between towns so you aren't just floating in space forever.

**Comment by 7yl4r** [comment]
@MrNubbin, that's an interesting suggestion. I think this is a feature we can add from the software design side though. Simple x2, x10 speed or similar plus some extra explanation in there somewhere. Let's open a new issue for further discussion on that.

**Comment by 7yl4r** [comment]
@terpin I'm not sure I follow what you mean. If we have separate tiles of a set height, then we can put them together to any length needed. To keep it from getting too boring we can introduce more tiles. 

So let's say we want a section of space to be 9000px, we can approximate that size by assembling tiles which are 5k, 4k, and a 1k wide. We're lucky in that space has a lot of black, so matching edges shouldn't be too much of an issue.

**Comment by terpin** [comment]
Ohhh, I was going to actually paint all those out!

**Comment by 7yl4r** [comment]
Well, you can! I just think we ought to break it into sections so that we can reuse some of them. Scrolling across at 10px/sec for an hour is 36000px, after all... and that's for the small layer. Passing by planets can be unique, but there is a whole lot of blackness and white specs which you'll probably end up copypastaing anyway. Plus, if we use tiles, it get easier to assemble different trajectories later on.

**Comment by 7yl4r** [comment]
after looking/thinking a bit more, I think 600px is the way to go - 400px looks too small. Are you still up for painting these @terpin? I hope my tiling idea didn't deter you; it's by no means set in stone.

**Comment by terpin** [comment]
Yeah I'm still down for it. We'll try tiling, if it ends up looking bad
I'll just paint long ass scenes, it's no biggy (I just finished one up the
other day 6,500px wide, haha)

**Comment by terpin** [comment]
I'm setting up all the planets for painting now, but I'm not sure which
earth to go with!

Day or Night?

**Comment by 7yl4r** [comment]
that's a tough call. [both? =P](https://lh3.googleusercontent.com/proxy/3tygcr8tffgsZOehsr8O200cka0Tvry7UBFU2SR3S9Q0K07cgSlCyNCXiQjvPlENx6YRABO-8yhZ-KoB_lsHI632NMO97l9REUnj47L9bYcFwDgeHwmEiCuhtavRQ17SrGdpymhp=w426-h323-p)

**Comment by terpin** [comment]
WHY YOU GOTTA BE SO GREEDY OP?

**Comment by terpin** [comment]
Maybe depending on when you leave you get a different little earth screen?!

**Comment by 7yl4r** [comment]
Sure! You're the badass artist here though, it's your pick.

Maybe it's best we come back to add the 2nd one after we get the other places though. I don't want Earth hogging all your time when there's all those other awesome places to visit. =)

**Comment by terpin** [comment]
You don't tell me what to do Jimmy!

**Comment by terpin** [comment]
Hey guys! Here's Earth!



(big imgur link: http://i.imgur.com/mr441CH.png)

This should connect to the moon background tile when done, hopefully
seamlessly! Since earth and the moon are so close together I'm going to
have the moon oriented on the next tile like earth, but with the next
planet (mars i think) it'll be spaced a lot further apart. Good width? Let
me know!

**Comment by MrNubbin** [comment]
WOW!!!

**Comment by terpin** [comment]
THE MOON WILL BE AWESOMER!

**Comment by 7yl4r** [comment]
omg this is gorgeous. I'm so excited to see more! The width can be whatever you want! Empty space is easy to add, after all.

**Comment by terpin** [comment]
I'm avoiding stars and trying to make sure everything is black-black at the
ends so you can crop/extend if you need to.

**Comment by 7yl4r** [comment]
Yeah, I think that's the way to go. I'll put this in the demo later tonight so we can take a look at it with the milky way behind it.

**Comment by terpin** [comment]
Awesome let me know!

**Comment by terpin** [comment]
Do you guys think I should have a little earth in the background of the
moon tile?

**Comment by 7yl4r** [comment]
If you'd like to, sure! Since the background view right now remains fixed to the stars behind, we should probably be seeing things swing by multiple times as we orbit anyway. It feels a bit weird to have "2 earths" in the background, but when you think a bit harder, it's actually just fine. Maybe it's good to make people think harder anyway! =)

**Comment by terpin** [comment]
Woo! The seem to blend together super well! I was looked at the trajectory
map as a guide.

http://i.imgur.com/a518YHZ.jpg

Also, TIL you can see Saturn from the moon, it's just teeny tiny!

**Comment by 7yl4r** [comment]
These backgrounds are truly epic. They look so great [in game](http://7yl4r.github.io/the-oregon-trajectory/)

**Comment by terpin** [comment]
I think I may need to put some stuff in the big empty between earth and the
moon (and the other spaces too), i wasn't sure if my ship was moving or
not, kids might get confused

**Comment by 7yl4r** [comment]
The best way to handle this is to fill that space with events, random debris, or other ships I think. If you want to draw up some little tiles of this nature, I can then add them in procedurally. However, this can also be mitigated with sprites.

Ideally we won't have long spaces in the actual game, because things will be happening; maneuver sprites, ship wreckage, and all that jazz.

**Comment by terpin** [comment]
Okay sounds good!

**Comment by 7yl4r** [comment]
... in terms of things to add, it'd be great to add things like the hubble, james webb telescope, and other things that give opportunity to link out to cool educational content.

**Comment by terpin** [comment]
okay. I'm going off that trajectory map on the wiki to know where to put
the planets in the background as they travel along the route. That's pretty
much what we're going off of, yeah?

**Comment by 7yl4r** [comment]
That's the trajectory, yes. I do think it's best we handle placement in the code and we keep art sectioned into tiles though. That way you don't have to work on one big piece and we can re-use sections if we tweak the trajectory during gameplay. For instance, if you decide to pass on the maneuver node until your next orbital pass, we can re-show the previous tile. 

So what we really want is a bunch of different files with a common height of 600px, which are black at the left/right edges, and whatever width you feel like.

Does that make sense?

**Comment by terpin** [comment]
That feeling when you suddenly realize that you've bit off more than you
can chew:

http://i.imgur.com/Yj2NrJg.png

Jupiter is kinda sorta huge.

**Comment by 7yl4r** [comment]
O.O

**Comment by terpin** [comment]
This one... it might not be so detailed other than the red spot... because
i kinda sorta want to keep my mind :D

**Comment by 7yl4r** [comment]
dont stare at ![this](https://upload.wikimedia.org/wikipedia/commons/7/76/PIA02863_-_Jupiter_surface_motion_animation.gif) too long...

**Comment by terpin** [comment]
oh no! i've lost my mind!

**Comment by JesusVidal** [comment]
Nicee *-*

**Comment by 7yl4r** [comment]
now I'm trapped in the wiki article about Jupiter's atmosphere, help!

**Comment by terpin** [comment]
Enjoy that gravity well there buddy!

**Comment by terpin** [comment]
Do we use something more yellow:

http://i.imgur.com/zf2a5Pb.png

Or do we use something more blue:

http://i.imgur.com/2iSKpFq.png

?

**Comment by JesusVidal** [comment]
Both of them look awesome, however for me, Yellow looks better.

**Comment by terpin** [comment]
Well I'll put it to a vote and let you guys decide. finishing up mars
hopefully tonight!

**Comment by 7yl4r** [comment]
The beauty of these still blows my mind... I'd vote... uhhh... yellow also.

I don't know if you caught it in the gitter chat, but we're thinking of changing up the v1 trajectory so we end in the asteroid belt and maybe swing back to Earth (the maneuver will definitely include Jupiter, even if just for the sake of this awesomeness). We're still a bit on the fence about it, but if we do switch then you could have some time for character or location art. What do you think?

**Comment by terpin** [comment]
I just wanted it to be enormous and make the poor kids have to trek all the
way across the thing.

Do you know what would be cut, planet-wise? After Mars I hadn't done any
research or planning but it should be okay, I just need to know what we're
doing beyond that. Would we be adding an asteroid field? What other
locations?

**Comment by 7yl4r** [comment]
I _really_ love how huge it is. I hope everyone who has to cross it thinks "jeez this thing is huge" =)

The new trajectory might be something like:
Earth, Moon, Mars, Ceres, Jupiter (Europa) and then back... maybe skipping some things. @MrNubbin will have to help me out a bit here.

**Comment by terpin** [comment]
Okay, I'll just wait to hear back from you guys :) Make sure you make a
list of what we're keeping (so i can go into the project folder and delete
anything superfluous) and what we're adding so I can figure out what's
feasible in the next 10 days

**Comment by 7yl4r** [comment]
definitely hold off on Uranus, Neptune, Pluto/Charon for now. Mars & Ceres we will want no matter what.

**Comment by MrNubbin** [comment]
In terms of justifying going to Jupiter instead of an asteroid, Europa has a lot of scientific interest. It'd make more sense to go there as opposed to another asteroid. The purpose with ARM is to bring an asteroid to Earth's orbit and then more easily study the crap out of the thing. After studying that asteroid I'd like to think another planet's moon would be more interesting. So lets do that moving forward.

**Comment by MrNubbin** [comment]
Just to clarify that means, earth, moon, mars, ceres, maybe other asteroids, jupiter, and europa to be drawn.

**Comment by MrNubbin** [comment]
For inspiration click [here](https://www.youtube.com/watch?v=Q6goNzXrmFs)

**Comment by 7yl4r** [comment]
The more I think the more I like this new plan. We could work in a lot more about asteroids this way, and have the player go through several asteroid-stations to stock up before a science mission to Europa.

**Comment by JesusVidal** [comment]
That video, just get reminded of A pale blue dot :^)
