### ISSUE TITLE
game story draft

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#22]
Get draft of the main story on the wiki

**Comment by 7yl4r** [comment]
reference [this early storyboard](https://docs.google.com/presentation/d/1ihHx87kblOmQkT12vq68Q_uwOBYdLQET56Rgdd7GUQY/edit?usp=sharing) and the more up-to-date [trajectory plan](https://github.com/7yl4r/the-oregon-trajectory/wiki/Trajectory-Plan) for inspiration.

**Comment by MrNubbin** [comment]
Thanks for the starting point. I'll slap most of this together tonight.

**Comment by MrNubbin** [comment]
Sorry I took so long! Here is my [first draft](https://docs.google.com/presentation/d/1trmPsQiFNQtOHnaCyKzaeCg-4O-M7eOH3YFqmbBeQ4A/edit?usp=sharing). Thank you for that early storyboard, it was a big help. I am missing random events, some "town" dialogue, and the "learn about the trajectory". I'm not sure how the first 2 are going to be incorporated yet but what were we thinking for the "learn about the trajectory"  section from the main menu. Is that talking about the game in general or trajectory specifically.

**Comment by 7yl4r** [comment]
Sweet! This was well worth the wait; there's a lot of great stuff there. 

The "learn about the trajectory" should maybe be renamed "learn about the 21st century terrestrial exodus" or something like that to talk about how spacetravel became more popular and available to the public thanks to driving forces like asteroid mining.

I was looking at [the challenge description](https://2015.spaceappschallenge.org/challenge/asteroids-2025-2100-future-history/) some more the other day and feeling like we're not talking about asteroids enough. Maybe this is one opportunity to bring them in a bit more.

I think it might be fun to include some science in the "learn about the trajectory(s)" aka "ask for advice" page where you are choosing 1mo, 2mo, 3mo, etc though.

**Comment by MrNubbin** [comment]
Great points! I agree and will work on them.

**Comment by 7yl4r** [comment]
I'm marking this resolved since I think your storyboard satisfies our current needs perfectly.
