### ISSUE TITLE
Create Trajectory

### ISSUE THREAD

**Issue by MrNubbin** [7yl4r/the-oregon-trajectory#23]
Create the trajectory as outlined in the trajectory plan wiki. Then take a bird's eye view screenshot of the trajectory and post it here.

**Comment by 7yl4r** [comment]
oh yeah, the graphic. Good idea!

**Comment by MrNubbin** [comment]
So uh... without going into detail, I ran into some hiccups. I should still be good for the 31st, but I'm just giving everyone a heads up.

**Comment by terpin** [comment]
I hate it when grues eat my work! Damnable grues!

**Comment by MrNubbin** [comment]
*shakes fist*

**Comment by 7yl4r** [comment]
can we help somehow? I always carry a spare lantern and batteries.

**Comment by MrNubbin** [comment]
If one of you guys can compile some fortran code then yes. Before you get too excited (or afraid) it's just converting data.

**Comment by 7yl4r** [comment]
is a map still incoming or should we need to bring an artist in on this?

**Comment by MrNubbin** [comment]
I thought the intention was I give a blueprint of the trajectory and then an artist (probably @terpin) was going to do a pretty render of it. (not to add to your plate!)

So I wanted to get a legit trajectory but of course I'm running into problems I didn't foresee. I thought it'd be easier since I just had to do the fly-bys and not actually worry about fuel consumption well... fuel is not the problem, the fly-bys are the hard part haha.

SO! Here is what I propose, I'm going to draw up a trajectory using very advanced MS Paint techniques (or I can try to do something better) When the artist beautifies it, is there a way to keep the planets as like separate objects? This way when I do develop a trajectory in the future (v2.0 or whatever) you can just move the planets to the correct new position in the orbit? Seems like the best plan for now. Again, I way overestimated my abilities here. There's a reason missions take years to plan... I should know better.

**Comment by terpin** [comment]
I can just save it as a layered PSD, that way if anyone needs to go back
later and move things around on the map they can. I'm sure there's some
non-proprietary format we could use, but PSD is pretty standard. What do
you guys think?

**Comment by MrNubbin** [comment]
As long as someone else has access to that file in the future that sounds pretty good to me.

[Here](http://i.imgur.com/ZEGio4D.png) it is. I'm actually happy, this isn't a fully refined trajectory but it is definitely realistic/plausible! I was just looking at numbers before so I didn't even realize how out of position uranus and pluto are in the 2040-2100 time constraint we have. So we need to change the trajectory order from:
Saturn->Uranus->Neptune->Pluto
to:
Saturn->Neptune->Uranus->Pluto

I'll update the wiki for that change as well as get Ceres and Halley's in the right place. I'm going to leave this open until the final product is developed. Passing it to you @terpin. Let me know if you need anything else!

**Comment by MrNubbin** [comment]
Craaaaap. I was working on determining a mission duration and its like 100+ years. So yes, the trajectory there flys by all the planets but there isn't really a quick way to do it... so do we want to glaze over that or head on out?

**Comment by 7yl4r** [comment]
Well, I see two good options: 1. carry on as planned, dont mention time at
all for now 2. Come up with a shorter trajectory. Probably returning to
using the asteroid belt as destination... Story can talk about a mining
colony or something there. (that fits a bit better w/ the challenge
description too)

**Comment by MrNubbin** [comment]
Ok so [here](http://i.imgur.com/00onspp.png) is the new trajectory and its only 4 years and some change (woo!). Here are the associated travel distances:
1. Launch->Moon Maneuver Node: 0.0015 AU (228767 km)
2. Moon Maneuver Node - > Moon Rendezvous: 0.0015 AU (228767 km)
3. Moon Rendezvous -> Mars Maneuver Node: 1.9608 AU (293,341,758 km)
4. Mars Maneuver Node -> Mars Rendezvous: 1.9608 AU (293,341,758 km)
5. Mars Rendezvous -> Ceres Maneuver Node: 1.6243 AU (242,993,682 km)
6. Ceres Maneuver Node -> Ceres Rendezvous: 1.6243 AU (242,993,682 km)
7. Ceres Rendezvous -> Jupiter Maneuver Node: 3.2486 AU (485,987,365 km)
8. Jupiter Maneuver Node -> Jupiter Rendezvous: 3.2486 AU (485,987,365 km)
Total distance: 13.6719 AU (2,045,295,347 km)

Closing.
