### ISSUE TITLE
milky way & it's tilt 

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#27]
backgrounds may inevitably contain a view of the milky way. This may be a good opportunity to explain the milky way and [how it is tilted](http://physics.stackexchange.com/a/148248) in the view.

**Comment by terpin** [comment]
Inevitably, you say?!

**Comment by 7yl4r** [comment]
technically, most things we can see are views of the milky way. =P

**Comment by JesusVidal** [comment]
So, maybe made the milky way part of the background? That'd look awesome!

**Comment by 7yl4r** [comment]
The background I'm using behind the art right now actually is a section from a 360 composite image of the milky way which I attempted to manually align so that the ecliptic plane falls along the direction of travel and the neglected "z-axis" coming out of the screen.

It moves very, VERY slowly as you progress through the game.

**Comment by 7yl4r** [comment]
moved to the wiki's new [content dump](https://github.com/7yl4r/the-oregon-trajectory/wiki/Content-Dump).
