### ISSUE TITLE
iterate on storyboard

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#3]
The storyboard needs a looking over, in particular we need to address [the comments of /u/ccricers](http://www.reddit.com/r/gamedev/comments/2zznbc/its_the_rgamedev_daily_random_discussion_thread/cpo9aya)

**Comment by 7yl4r** [comment]
oh.. can only assign a task to one person at a time... oops. Well, I'd like to discuss what starting options players get and how they change things later in the game. What are your thoughts on this @MrNubbin , @BrianErikson ?

**Comment by MrNubbin** [comment]
For random events I was thinking solar flares, random maintenance requiring parts/EVAs, EVAs for random debris/samples to collect (mini game?), collision avoidance (throw a probability of collision at them and have them make a decision), take a page out of Fallout and have rad pills (radiation is the new dysentery), and maybe have a psychology factor (you only brought 3 songs to listen to for 5 years, have fun with that).

How this correlates to starting options is:

-How protected are you from radiation? (you and your electronics; you get sick or solar flares break random things)
-Quality of your spacecraft
   -Entertainment
   -Life Support
   -Quality communication to Earth
   -Etc.
-Spare parts
-Spare fuel for EVAs (used for repairs and the debris collection mini game)
-Extra spacecraft fuel for emergencies

Here's another idea, choose one out of your 5 crew mates. Get a rich guy and you get more money but he may drive you crazy, vise versa, or someone in-between.

**Comment by 7yl4r** [comment]
These all sound like great ideas. In the original it was as simple as choose banker/farmer/whatever, and then buying parts. I think we might replace that with a set of points to allocate to the areas you've outlined, since i'm not sure what the space-age equivalent of farmer/banker etc are...

**Comment by JrodManU** [comment]
Planet farmer, Intergalactic banker, and a space ship mechanic.

**Comment by 7yl4r** [comment]
ideas here moved to [wiki page](https://github.com/7yl4r/the-oregon-trajectory/wiki/gameplay,--resource-management,-event-modifiers,--starting-options), now moving on to story draft
