### ISSUE TITLE
change the travel button dynamic

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#31]
how can we improve upon the "click & hold to travel" dynamic?

In space you keep moving whether you want to or not. Perhaps this should be "click to accelerate". But then do we have players worry about decelerating on approach to a station? can we automate that somehow or is this is a slow down or you lose dynamic? 

What sounds most fun?  

I think I like the challenge of manual slowing down (b/c then speedruns become fun), but maybe it's already hard enough if you have to watch your fuel usage.

**Comment by BrianErikson** [comment]
Personally I think we should stay true to Oregon Trail in this case, and just keep traveling unless an event occurs. Controlling speed should be entirely irrelevant when it comes to fuel conservation -- the idea is to get enough supplies to hold you over until the next opportunity to get more supplies. 

On the other hand, if we're branching away from Oregon Trail, it would be interesting to only allow events to happen if you visually see them and slow down to a stop to trigger the event.

**Comment by 7yl4r** [comment]
I think you're probably right. Let's stick with the oregon trail's way and maybe do some tweaking after we get through the first version.

**Comment by 7yl4r** [comment]
This is my favorite add-on feature though, so expect some work on this in v1.0.1. =P

**Comment by BrianErikson** [comment]
@7yl4r, when you get a chance, go ahead and close this one out (since we implemented a new version), and open a new issue for this as a content suggestion/enhancement so we can keep track.
