### ISSUE TITLE
glyphicons mismatched

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#32]
glyphicons don't seem to be loaded correctly, glyphicon-cutlery appears to be a small [16]? also there are two related error messages in the console:

```
GET http://localhost:8000/assets/Flat-UI-master/dist/css/fonts/glyphicons-halflings-regular.woff 
GET http://localhost:8000/assets/Flat-UI-master/dist/css/fonts/glyphicons-halflings-regular.ttf 
```

I thought I fixed this earlier by using bootstrap's cdn for the icons, but I guess not.

**Comment by 7yl4r** [comment]
this issue isn't resolved for me. The "rations" glyph still doesn't work and the errors are still showing when loading the travelScreen page. Sorry for taking so long on this.

**Comment by BrianErikson** [comment]
It seems the fonts are referenced by Flat UI in two seperate directories for some reason. A simple fix would be to add these fonts *again* into the directory it's referencing... Obviously this is a hack at best, but unless we want to modify Flat UI's references, this might be the best way to go.
