### ISSUE TITLE
travelscreen ui does not update while traveling

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#39]
auto-travel (6ea1c9442d2288b4117092a1681b668baac0abbe) is for some reason preventing the ui display from updating. In theory, things should be the same as before, but apparently angular handles things triggered by ng-hold differently than changes triggered by setTimeout. Hopefully there is some way to force angular to update values.

**Comment by BrianErikson** [comment]
@7yl4r, check out [`$interval`](https://docs.angularjs.org/api/ng/service/$interval). I'm still learning how to implement stuff in angular, but it looks promising for this use-case.

**Comment by 7yl4r** [comment]
nice. that was a lot easier than I expected.

**Comment by BrianErikson** [comment]
Yeah I was actually pleasantly surprised that it almost replaced setTimeout one-to-one.
