### ISSUE TITLE
Scale ship to 50% of current size

### ISSUE THREAD

**Issue by BrianErikson** [7yl4r/the-oregon-trajectory#42]
The ship appears quite large in relation to the viewport right now, what do you guys think about making it smaller?

**Comment by terpin** [comment]
I think that may also be a bit because I did the planets a little large,
sorry about that Pixel Dude. Could we try rescaling the ship to 33/50/66.7%
and see which one works best?

**Comment by BrianErikson** [comment]
This can all be dynamically scaled in `JavaScript` fortunately. I'm just curious to see what everybody thinks since I wasn't the one to implement the ship

**Comment by 7yl4r** [comment]
I agree that it does look a little big as it is.
