### ISSUE TITLE
tweaking the rocket sprite

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#43]
we'd like to get some variations on the existing rocket sprite to allow for non-player ships and maybe even a "customize your rocket" module in the future.

Different colors or shapes added, maybe add some damage or extra gear to the rocket, feel free to be creative! (without deviating too far from the sprites' hexel art style).
##

**Comment by JesusVidal** [comment]
I am thinking of a game I played a long ago Ill try to find it also Ill create some models

**Comment by terpin** [comment]
I love your ships man! Is it hard to change the color for those?

**Comment by 7yl4r** [comment]
> I love your ships man! Is it hard to change the color for those?

what? huh? what did I miss?

**Comment by terpin** [comment]
I mean of his sprites with the hexel editor, he was talking about making
different ones for different engines earlier and I was wondering how hard
it was to change the color of the sprites

**Comment by 7yl4r** [comment]
ah, I see. @JrodManU's the official sprite man, @JesusVidal is looking for an entry point and this seemed like it could be a good fit. I believe @JrodManU did once say that hexels makes color changing easy though...

**Comment by terpin** [comment]
Oh damn ^^ I thought maybe Jrod was Jesus and it was just displaying as
Jesus instead of Sprite Man ^^ So sorry!

**Comment by JesusVidal** [comment]
So I search for 8-bit spaceships and found this, also pass it to Hexels and I think this can be a first prototype for the ship, please let me know if its ok to use the models.
![prototype](https://cloud.githubusercontent.com/assets/11733336/6935597/a94a51a8-d80d-11e4-9105-5a20889583c2.png)

**Comment by 7yl4r** [comment]
sweeeet.

**Comment by 7yl4r** [comment]
This is issue is old and I've ported in everything I can (spritesheet made from image above called ship_vidal.png)
