### ISSUE TITLE
random event sprite

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#52]
I'm ready to add random events in the code and I need a sprite to use on the travelScreen. 

I'd most like it to be a small asteroid encounter (smaller than the ship), but if you're more inspired to make a sprite for a different event from [the list](https://github.com/7yl4r/the-oregon-trajectory/wiki/random-events), that's fine with me too.

@JesusVidal , you or anyone else capable of making a hexels-style sprite are welcome to take this over if @JrodManU doesn't mind.

**Comment by JesusVidal** [comment]
I was thinking of space junk such as broken satellites  or orbiting objects. I know it has to be improved, but what do you guys think of the idea?
![satellite](https://cloud.githubusercontent.com/assets/11733336/6975326/861c138e-d960-11e4-957c-461414155ee1.png)

**Comment by 7yl4r** [comment]
I like this a lot! Can I get a version with a transparent background?

**Comment by JesusVidal** [comment]
Sure!
![satellite](https://cloud.githubusercontent.com/assets/11733336/6975845/6f934e78-d967-11e4-94a4-ba10944faecd.png)

**Comment by terpin** [comment]
very nice!

**Comment by JesusVidal** [comment]
My asteroids look awful u.u
![asteroid - c](https://cloud.githubusercontent.com/assets/11733336/6994090/1d83b6ba-dad2-11e4-9e08-25ea3a74ba43.png)

**Comment by JesusVidal** [comment]
![asteroid - nc](https://cloud.githubusercontent.com/assets/11733336/6994098/5acd5044-dad2-11e4-8982-6706ecff748e.png)

**Comment by 7yl4r** [comment]
I've never understood how people draw "rocks" and make them look good; I always end up with brownish blobs. Maybe some more space debris? I hope to have events up and running soon, hopefully from there we can open up for writers/artists to add events.

**Comment by 7yl4r** [comment]
Also: what about re-creating the International Space Station in the style of that debris satellite?

**Comment by JesusVidal** [comment]
Whoa that would look nicee, I ll try it.

**Comment by JesusVidal** [comment]
You know ISS is huge when you need more space and just made 20% of it...
![iss](https://cloud.githubusercontent.com/assets/11733336/6995054/73bf3702-daf5-11e4-8a68-78f18480306b.png)

**Comment by JesusVidal** [comment]
Guys, this a prototype, what do you think? I think I exagerate in the size of the medium part...
![iss prototype](https://cloud.githubusercontent.com/assets/11733336/6996093/e2e34196-db36-11e4-8262-86d3519e99de.png)

**Comment by 7yl4r** [comment]
Ohhh yeah. that's the stuff.

**Comment by JesusVidal** [comment]
Should I add other details? or maybe go to the other objects...

**Comment by terpin** [comment]
Well we've got a week until it officially kicks off. If I were you, I'd
work on having everything done, then go back and detail things as needed.
Better to have all our assets in place than a few really good assets and
others that look kinda ehhh, if you know what I mean

**Comment by JesusVidal** [comment]
Got it, I'll move on with the other stations

**Comment by 7yl4r** [comment]
This issue got a bit de-railed (in an awesome way), but it was solved way back with the satellite sprite.
