### ISSUE TITLE
Update wiki/storyboard/images with new mission plan

### ISSUE THREAD

**Issue by MrNubbin** [7yl4r/the-oregon-trajectory#56]
Since we figured out the trajectory is like 100+ years... we decided to change the trajectory. We will be going to Europa instead of Pluto.

**Comment by JesusVidal** [comment]
It sounds more interesting, have you figured out which asteroids should we put like stations in this new trajectory?

**Comment by 7yl4r** [comment]
just going to leave this here for reference in case someone is looking:

> earth, moon, mars, ceres, maybe other asteroids, jupiter, and europa

**Comment by terpin** [comment]
Will these be the location art locations, too, if that makes any sense?

**Comment by 7yl4r** [comment]
I think so, yes. We ought to establish a bit of lore behind each. For instance, the Europa station is a sub-surface science outpost studying the ocean (life?) under the icy surface, the base on Ceres is Planetary Resource's main asteroid-mining hub full of space-roughnecks, the Mars colony is inside of lava tubes... etc...

Maybe it's best we take these on writing/art/sound one at a time as a team?

**Comment by terpin** [comment]
We could, but is it technically feasible in our timeframe; e.g.: do we
really think we can coordinate and complete one each day for the next week?

**Comment by 7yl4r** [comment]
doing it this way we could theoretically split into sub-teams with 1 writer, artist, and sound on each. We do need to build out the first one as an example though.

**Comment by JesusVidal** [comment]
I think it's a good idea, focusing on making each of the stations, background art and the sound for every place on this trajectory

**Comment by terpin** [comment]
Well it takes me 5 hours to do a scene, so the two planets left in the game
would be 10 hours, plus another 35 hours of location art on top of that,
plus whatever time it takes to collaborate, that gets really heavy on top
of my work schedule.

I'll complete the two planets left (mars and ceres), but maybe @JrodManU
can take the location art off my hands? Is that okay with you @JrodManU?

**Comment by MrNubbin** [comment]
Is it my understanding that due to the time constraint we only have time to develop Earth->Moon->Mars->Ceres->Europa? That seems like the best plan moving forward. We can always continue to develop afterwards but lets get some results out for now. I'll start work on the background for each station location. If we do have time, lets add Vesta and Pallas so that the new order would be Earth->Moon->Mars->Vesta->Ceres->Pallas->Europa

**Comment by 7yl4r** [comment]
I think it's best to hone in on a few locations. Let's collect together everything for each location [on the locations wiki page](https://github.com/7yl4r/the-oregon-trajectory/wiki/Locations), or else make a separate page for each location.

**Comment by MrNubbin** [comment]
nah, ill keep it all together.

**Comment by JesusVidal** [comment]
I have to ask, if we are doing a base on moon surface, or either an orbital station which is supplied by a surface base, should I do a building and it will be placed on moons background art? remember that the sprites are kind of pixel art? please let me know to start faster

**Comment by MrNubbin** [comment]
lets do an orbiter for simplicity.

**Comment by JesusVidal** [comment]
What about this station for the moon?
![moon station](https://cloud.githubusercontent.com/assets/11733336/7054036/5626197e-ddff-11e4-81fd-6734211d28b3.png)

**Comment by 7yl4r** [comment]
@JesusVidal, I like it, but we've got a few [animated stations](https://github.com/7yl4r/the-oregon-trajectory/tree/master/assets/sprites/trajectoryStuff) already from @JrodManU. I'd like to see more in the style of [your satellite debris](https://github.com/7yl4r/the-oregon-trajectory/blob/master/assets/sprites/debris-satellite.png) or perhaps more existing objects like the Hubble or James Webb Space Telescope. Are there any other existing/near-future objects we might want to include, @MrNubbin ?

**Comment by terpin** [comment]
Also did we settle on which asteroids we're visiting, so I can both create
a little background screen + add them to the map? (and also, need the
trajectory asap! we got 4 days! hustle!)

**Comment by 7yl4r** [comment]
@MrNubbin dropped [this](http://i.imgur.com/00onspp.png) trajectory update in the chat. The extra asteroids are "add-ons" that we're leaving off unless we have manhours to put on extra content.

**Comment by MrNubbin** [comment]
Sorry about the delay @terpin!

James Webb is going to be at L2 and not necessarily close to the Moon. We could put the Apollo lander and flag on the moon? There are also the GRAIL missions which are just satellites in orbit around the moon.

**Comment by JesusVidal** [comment]
Got it, I'll make the hubble telescope and the other objects!

**Comment by MrNubbin** [comment]
Oh I thought we were just talking about moon missions. [Maven](http://lasp.colorado.edu/home/maven/) is doing some science around Mars. India's space program also has a mission to mars called [Mars Orbiter Mission](http://en.wikipedia.org/wiki/Mars_Orbiter_Mission) I think that should definitely have a "Hi MOM" joke but that's just me. [Juno](http://missionjuno.swri.edu/) will be studying Jupiter.

Not sure if all these will still be there in 35 years but whatever haha.

**Comment by terpin** [comment]
Yeah apparently jupiter's red spot is shrinking each year, but I made an
aesthetic decision to keep it enormous :D don't feel bad.

**Comment by terpin** [comment]
Hey guys, how am I supposed to depict maneuver nodes on the map?

**Comment by MrNubbin** [comment]
We could do like a generic waypoint sort of thing? Like a diamond? Did we make a maneuver node sprite? maybe it should resemble that

**Comment by 7yl4r** [comment]
I agree, a small, geometric marker is all we need. We haven't set a sprite yet, but we need one soon. #60

**Comment by terpin** [comment]
http://i.imgur.com/yF9ku5l.jpg?1

It's a map!

I put placeholders in for the nodes but this is pretty much done now! There
are other planets but I hid those layers since they don't really matter in
the trajectory :) Someone else will have to overlay the trajectory because
my line work skills are honestly pretty weak.

**Comment by JesusVidal** [comment]
It's a Telescope! 
![hubble telescope](https://cloud.githubusercontent.com/assets/11733336/7083534/c4da90aa-df28-11e4-8bfe-a1417606ec79.png)

Say hi to Hubble :3

**Comment by RyleeSparkles** [comment]
@JesusVidal , sweeeeet.
