### ISSUE TITLE
establish art asset style

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#7]
I think we'll need only a handful of assets for the main storyline (something analogous to the wagon, oxen, shopkeep, location sprites in the original), but there is also the large (pixel-art) graphics for each location. I think we need to maintain a coherent style with the "sprite" assets, but the larger graphics could be done by different people.

You can watch this Oregon trail playthrough on youtube[1]   or look for my [pic of whatever here]s in the storyboard to get an even better idea of the scope.

**Comment by AshlynnInWonderland** [comment]
I'm personally a huge fan of the hexels that JrodManU has been using so far. I think it's a very nice stylistic approach for the art style.

**Comment by 7yl4r** [comment]
The consensus seems to be that the hexels are great for sprites (we can do sprite animations w/ this too, yes?), but I think we want to branch out for some of the larger assets. I mean, just think of all those pretty NASA photos we can pull in.

**Comment by AshlynnInWonderland** [comment]
Have we looked at how they look together yet? Or will they be kept mostly separate?

**Comment by terpin** [comment]
You'll want to assign JrodManU all the sprite assets then, but I'm not
really sure how realistic NASA photos would look behind those hexels,
honestly. Even if I used them as a base for a matte painting, it might have
a chintzy "slapped together" feel. You may just want to assign all art
assets to one person to give it a more cohesive look.

**Comment by JrodManU** [comment]
We haven't really tested them together

**Comment by terpin** [comment]
I'm just saying if you go with a vector/pixel/such art style, you'll want
to stick with it throughout. It, much like a rug, ties the room together. :D

**Comment by AshlynnInWonderland** [comment]
I can see the merits of mixing the styles, but I think it'll have to be done very well or it won't look good.

**Comment by AshlynnInWonderland** [comment]
I don't think just hexels would look that good, though. We'd probably have to just go to mostly flat backgrounds if we were doing that.

**Comment by 7yl4r** [comment]
I think I agree w/ @AshlynnInWonderland, going full-on hexels means that we'll lose a lot of awesome in the backgrounds unless a lot of time is spent crafting hyper-detailed hexel art backgrounds. Our best option is to find a way to mix them or to switch in and out of the hexel style depending on the scene. I think @terpin should get final say on this though, since he seems to have the best design chops among us.

**Comment by terpin** [comment]
Haha I am @terpin, but yeah. Me and @JrodManU are going to try and make
sure everything meshes well together. It'll be tricky, but I'm sure we'll
figure it out :) Pretty sure I can just matte paint the scenic backgrounds
like http://i.imgur.com/BtSvie9.jpg should be okay as long as we can figure
out how everything works together on the screen :)
