### ISSUE TITLE
[shop] only the shop greeting sound works (old ubuntu/chromium)

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#77]
My older laptop doesn't play most of the sounds in-game. Not sure why. Can provide additional specs, but I've tested and it works in newer versions so this is low-priority.
##

**Comment by jharrisonmusic** [comment]
Ive noticed this on places with poor internet,  I attributed it to the wavs being pretty big so they just are really latent on triggering.   If we want we could switch to mp3 for a much smaller file size.

**Comment by 7yl4r** [comment]
I'm using ogg/mp3 for the music for sure. I'm also confused why the greeting works but the click sound doesn't....

**Comment by akc2142** [comment]
Click sound works for me. I've been focusing on Chrome specs given we don't have a ton of time. Now the background music isn't playing though.

**Comment by 7yl4r** [comment]
@akc2142, no music? wahhht? What's your OS? Maybe I need to add some more fallback filetypes...

**Comment by 7yl4r** [comment]
I just realized... this can't be a network issue I'm seeing, since I'm running off localhost. Mine must be browser/OS incompatibility issues; this is a common pain point right now.

**Comment by 7yl4r** [comment]
closing this legacy issue to clear the issue tracker, but it remains open and tracked on the [legacy project board](https://github.com/7yl4r/the-oregon-trajectory/projects/3)
