### ISSUE TITLE
Sometimes travel continues while you're in an event screen

### ISSUE THREAD

**Issue by MrNubbin** [7yl4r/the-oregon-trajectory#81]
While you're deciding to trade that 100 fuel for 1000 food or something like that the travel continues without you knowing. This would kind of be ok but it messes up the positioning of the planets. I don't even see Jupiter/europa when I get there :(
##

**Comment by 7yl4r** [comment]
that's pretty odd. travel should stop when you switch from the travel module

**Comment by MrNubbin** [comment]
i cant get it to happen consistently though, and its not one specific event

**Comment by 7yl4r** [comment]
I haven't seen this at all. What browser/os are you seeing this in?

**Comment by MrNubbin** [comment]
Google Chrome, I think ive seen it in Windows 7 and Mac OSX 10.8

**Comment by 7yl4r** [comment]
closing this legacy issue to clear the issue tracker, but it remains open and tracked on the [legacy project board](https://github.com/7yl4r/the-oregon-trajectory/projects/3)
