### ISSUE TITLE
regroup to plan out next version

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#85]
I'd like to set up a timeline and some goals we want to roll out for future plans. Things to think about:

* what is your most desired feature/improvment
* what is the long-term aim (museum installment, educational game for schools)
* monetization/ads - I hate this stuff, but maybe we need some
* what is the next step? is there another competition or event we can use this for? Should we plan a release around something?

**Comment by terpin** [comment]
A few things, so far:

Art. It's a hodgepodge and we need to work on creating a more uniform
style. Jose's new sin culo spacecrafts are a good start.

Writing. We need to work on creating a timeline of events that take place
in the game, maybe find ways to tie outcomes from events earlier in the
game with ones later in the game. Random events are great and all, but we
need to flesh it out.

Minigames. The asteroid minigame is awesome, but we need a couple more. A
probe minigame could be a good idea, especially if it were someplace like
Mars where we could interlink with content on the NASA site about different
dead probes still on their surface, information about their missions, talk
about planetology junk, etc. I'm talking out my behind here so if it's not
doable, that's okay. Another minigame could be docking with stations or
having a maneuver node minigame.

As for monetization, we're better off finding sponsors than implementing
ads directly into the game - especially if you want to push this as an
educational game for schools. This is pretty much what I do for a living,
so take it from me when I say that most ad-based monetization models are
just abysmal (CPM/CPI can be as low as a half a penny per 1,000
impressions, it gets pretty nasty even if you can pull off high volume
traffic). If you want to go the studio route, we'd need to start raising
our visibility. There's a lot that can be done there, but studios come with
their own headaches (especially when it comes to getting paid).

I don't know any upcoming comps, but there's always something out there.

**Comment by BrianErikson** [comment]
I'd advise against monetization honesty; it creates a lot more problems than it solves. If monetization *is* necessary, though, what @terpin suggests is probably the way to go -- a single grant/payout is easy to distribute, recurring payments comes with a whole lot of red tape (and people would be getting pennies-per-month with ads).

**Comment by MrNubbin** [comment]
I agree with the writing; we need more structure but I still do like the random events. We can do stuff like "Oh look its *insert satellite name*, it's been in orbit around *some planet* since *insert date and other information about the mission*" (This could be through the Chronos API?)

Do we plan to go further into the solar system? I think there is a lot of value with what we're doing currently. The other planets are cool but asteroids are much more relevant now. I could definitely see a sequel to this going to each planet. It'd be a little different I think.

**Comment by terpin** [comment]
As an aside... are any of you guys or do any of you guys want to do Ludum
Dare this weekend?

**Comment by 7yl4r** [comment]
@terpin I'm willing to participate (in a much smaller capacity) for ludum, sure.

**Comment by jharrisonmusic** [comment]
I'd love to do Luden, let me know what you meed on the music side.

As far as taking trajectory further musically - I think if we're doing more mini games it could be cool to build those out some more with sfx and maybe their own music.  What do you guys see as priority in the sound area?

**Comment by 7yl4r** [comment]
Sound is being held back by a lack of code implementation more than
anything. Sound/music for the mini games and for the different stations
(not yet implemented) could be one thing to work on. Maybe also unique
sounds for particular events. Again though, these things aren't ready in
code yet. You did an epicly good job with the sound and I'm still catching
up. :)

**Comment by 7yl4r** [comment]
I think we're all in agreement about finding a sponsor instead of directly monetizing the game. 

I've put the sound updates into the v1.1 milestone.

In order to improve on the story with events we need to build onto the existing event handlers. I'd like to do some code cleanup before we start adding more functionality though. We could, however, work on building out the locations more. Story could be worked in along with the locations easily. Please create new enhancement issues for this if you have ideas and hopefully we can get them into 1.1

**Comment by 7yl4r** [comment]
@terpin , what is the low-hanging fruit in terms of improving the art? Should we switch over to @JesusVidal 's ship/station sprites since you think they fit better with the overall style?

**Comment by terpin** [comment]
I'd say yes!

**Comment by 7yl4r** [comment]
OK, I'll add it to the v1.1 milestone. Any purger smallish tweaks we can
make to improve artistic homogeneity?

**Comment by terpin** [comment]
Nothing minor that I can think of right now
