### ISSUE TITLE
establish story/dialogue-writing workflow

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/the-oregon-trajectory#9]
I'm not sure how to separate writing from the code, but I think it will help us bring in good writers to the project. I've got some thoughts in the readme on the use of dialogue trees, but I'm still fuzzy on how to plug these into our code. Let's pick a structure (or decide to just hard-code things in json, your call) and figure out how to use it from both writer & developer sides.

**Comment by BrianErikson** [comment]
Well, the criteria that I know a story needs to fit into is:
*Accessible by organized keys
*Easily exapandable

Unless you can think of something else to put into the criteria, I think JSON parsing would work perfectly; no need to reinvent the wheel on this. If you're worried about story authors being able to work with JSON, we can just have them commit to google docs or something and then we can translate to JSON manually.

**Comment by 7yl4r** [comment]
Do you think those dialogue trees are overkill? I think lemma's blog about branching and remerging is actually something we might deal with. Though I guess conditional dialogue isn't at all needed in v1.

**Comment by BrianErikson** [comment]
'"asteroid-module": {
  "situation": "You come upon an old stump. What do you do?";
  "s1": "Remove it."; 
  "s2": "Leave it.";
  "s1a": "You remove the stump. You find %% gold underneath.";
  "s2a": "You leave the stump alone. A passerby tells a tale about how there was gold buried around here somewhere long ago.";
}'

Does something like that work? I don't imagine us having Mass Effect-type conversations happening

**Comment by BrianErikson** [comment]
Another way to do it would just have a separate class that logs your conversation choices based on flags, which then influences which string you pull out of the JSON file. 

I guess it all depends on the type of story you guys want to weave. Seeing as it is supposed to be a two-day event, we don't want conversation chains to get out of control.

**Comment by terpin** [comment]
It is a two day event *and* a children's game. We could probably build out
a more in depth story in a later version, but you may not want to drive
yourself crazy with a zillion options that may or may not be utilized so
early on. What's the easiest and most effective way to implement choices on
your side?

**Comment by BrianErikson** [comment]
I'm the most familiar with implementing JSON objects, for sure. In my opinion, I think it's the best tool for the job, and for the time requirements we're working with. Hassling with a third party lib might hinder us more in the short-term than it would help.

**Comment by terpin** [comment]
I'm not the coder/decider guy here, but it sounds like that's the right way
to go then! Could always implement a third party lib with more options
later down the line if need be. Would it be hard to port JSON objects to
whatever-else-there-is in later builds?

**Comment by 7yl4r** [comment]
Yep, you guys are right. I was definitely over-complicating things because I'm a nerd who gets excited by dialogue trees. @BrianErikson's json encoding looks spot on.
